name: Build Shadowrocket Rules

on:
  schedule:
    - cron:  '0 23 * * *'
  push:
    branches:
      - main
    paths-ignore: 
      - '**.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run auto-build.sh
        run: python3 run.py
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
